(() => {
'use strict';
const canvas=document.getElementById('game');
const ctx=canvas&&canvas.getContext('2d');
const $=id=>document.getElementById(id);
const ui={menu:$('menu'),hud:$('hud'),upgrade:$('upgrade'),pause:$('pause'),gameover:$('gameover'),grid:$('upgradeGrid'),level:$('level'),wave:$('wave'),time:$('time'),kills:$('kills'),hp:$('hpBar'),xp:$('xpBar'),boss:$('bossBar'),bossHp:$('bossHpBar'),touch:$('touchControls'),joy:$('joystick'),stick:$('stick'),toast:$('toast'),error:$('runtimeError'),errorText:$('runtimeErrorText')};
if(!canvas||!ctx){throw new Error('Canvas could not be initialized');}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const rand=(a,b)=>a+Math.random()*(b-a);
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const fmt=t=>String(Math.floor(t/60)).padStart(2,'0')+':'+String(Math.floor(t%60)).padStart(2,'0');
let W=innerWidth,H=innerHeight,dpr=1;
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.floor(W*dpr));canvas.height=Math.max(1,Math.floor(H*dpr));canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize);resize();
const weapons=[
{id:'pulse',name:'Pulse Blaster',icon:'✦',color:'#67e8f9',rate:.45,damage:22,speed:680,range:850,shots:1},
{id:'shards',name:'Void Shards',icon:'◆',color:'#c4b5fd',rate:1.1,damage:28,speed:500,range:650,shots:3,spread:.45},
{id:'orbit',name:'Orbit Blades',icon:'◈',color:'#f0abfc',rate:0,damage:34,range:105,shots:2},
{id:'nova',name:'Solar Nova',icon:'✹',color:'#fb923c',rate:3.2,damage:90,range:180,shots:1},
{id:'frost',name:'Frost Field',icon:'❄',color:'#93c5fd',rate:2.1,damage:50,range:155,shots:1},
{id:'arc',name:'Arc Lance',icon:'⚡',color:'#fde047',rate:1.45,damage:65,speed:900,range:900,shots:1,pierce:2},
{id:'meteor',name:'Meteor Rain',icon:'☄',color:'#f97316',rate:4.2,damage:145,range:260,shots:2}
];
const upgrades=[
['damage','Overcharge','⚔','+20% weapon damage.'],['speed','Thrusters','➤','+15% movement speed.'],['magnet','Singularity','◎','+35 pickup range.'],['armor','Phase Armor','◉','-15% contact damage.'],['maxhp','Reactor Core','♥','+20 max HP and heal.'],['cooldown','Rapid Circuit','⏱','Weapons fire 10% faster.']
];
const keys={};
addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(k==='p')togglePause()});
addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
const touch={active:false,x:0,y:0,cx:0,cy:0};
function stick(e){const r=52,dx=e.clientX-touch.cx,dy=e.clientY-touch.cy,m=Math.hypot(dx,dy)||1,s=Math.min(r,m);touch.x=dx/m*s/r;touch.y=dy/m*s/r;ui.stick.style.transform=`translate(${dx/m*s}px,${dy/m*s}px)`}
ui.joy.addEventListener('pointerdown',e=>{touch.active=true;ui.joy.setPointerCapture(e.pointerId);const r=ui.joy.getBoundingClientRect();touch.cx=r.left+r.width/2;touch.cy=r.top+r.height/2;stick(e)});
ui.joy.addEventListener('pointermove',e=>{if(touch.active)stick(e)});
['pointerup','pointercancel','pointerleave'].forEach(x=>ui.joy.addEventListener(x,()=>{touch.active=false;touch.x=touch.y=0;ui.stick.style.transform='translate(0,0)'}));
const game={running:false,paused:false,over:false,t:0,kills:0,wave:1,level:1,xp:0,nextXp:10,spawn:0,bossAt:60,player:null,enemies:[],shots:[],gems:[],parts:[],texts:[],shake:0,last:performance.now(),cooldown:0,magnet:0};
let save={bestTime:0,bestLevel:1,coins:0};
try{Object.assign(save,JSON.parse(localStorage.getItem('nebula-survivors-v2')||'{}'))}catch(e){}
function saveIt(){try{localStorage.setItem('nebula-survivors-v2',JSON.stringify(save))}catch(e){}}
function player(){return{x:0,y:0,r:18,hp:100,maxHp:100,speed:230,magnet:120,power:1,armor:0,orbit:0,weapons:[{...weapons[0],level:1,cd:0}]}}
function showOnly(el){[ui.menu,ui.hud,ui.upgrade,ui.pause,ui.gameover].forEach(x=>x.classList.add('hidden'));el.classList.remove('hidden')}
function reset(){game.running=true;game.paused=false;game.over=false;game.t=0;game.kills=0;game.wave=1;game.level=1;game.xp=0;game.nextXp=10;game.spawn=.1;game.bossAt=60;game.enemies=[];game.shots=[];game.gems=[];game.parts=[];game.texts=[];game.shake=0;game.cooldown=0;game.magnet=0;game.player=player();showOnly(ui.hud);ui.touch.classList.remove('hidden');updateHUD()}
function toast(s){ui.toast.textContent=s;ui.toast.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>ui.toast.classList.add('hidden'),1300)}
function burst(x,y,c,n=8){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=rand(40,170);game.parts.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rand(.2,.55),c,r:rand(1,4)})}}
function enemy(kind='grunt'){const p=game.player,a=Math.random()*Math.PI*2,r=Math.max(W,H)*.7+rand(100,300),types={grunt:[40,55,14,'#45e0a8',1],runner:[28,120,11,'#fb7185',2],brute:[160,35,25,'#94a3b8',4],ranged:[80,45,16,'#60a5fa',3],elite:[520,65,30,'#a78bfa',10],boss:[2600+game.t*18,30,52,'#ef4444',40]},d=types[kind]||types.grunt,scale=1+game.t/240;game.enemies.push({x:p.x+Math.cos(a)*r,y:p.y+Math.sin(a)*r,hp:d[0]*scale,maxHp:d[0]*scale,speed:d[1],r:d[2],color:d[3],value:d[4],kind,boss:kind==='boss',shoot:rand(1,2.5)})}
function spawn(dt){game.spawn-=dt;if(game.spawn<=0){game.spawn=Math.max(.16,.75-game.t*.0025);let n=game.t>120?4:game.t>60?2:1;while(n--) {const q=Math.random();enemy(game.t>75&&q<.04?'elite':game.t>45&&q<.15?'brute':game.t>30&&q<.3?'runner':game.t>25&&q<.42?'ranged':'grunt')}}if(game.t>=game.bossAt){enemy('boss');game.bossAt+=90;toast('BOSS INBOUND')}}
function nearest(x,y,max=Infinity){let b=null,bd=max;for(const e of game.enemies){if(e.hp<=0)continue;const d=Math.hypot(e.x-x,e.y-y);if(d<bd){b=e;bd=d}}return b}
function damage(e,n){if(!e||e.hp<=0)return;e.hp-=n;game.texts.push({x:e.x,y:e.y-e.r-6,s:String(Math.round(n)),life:.6});burst(e.x,e.y,e.color,4);if(e.hp<=0){game.kills++;for(let i=0;i<(e.boss?14:e.kind==='elite'?4:1);i++)game.gems.push({x:e.x+rand(-10,10),y:e.y+rand(-10,10),v:e.boss?4:e.value});save.coins+=(e.boss?25:e.value)}}
function fire(w){const p=game.player,target=nearest(p.x,p.y,w.range||9000);if(w.id==='orbit'||!target&&w.id!=='nova')return;const n=w.damage*p.power*(1+.12*(w.level-1));if(w.id==='nova'){for(const e of game.enemies)if(dist(target,e)<w.range)damage(e,n);burst(target.x,target.y,w.color,18);return}if(w.id==='frost'){for(const e of game.enemies)if(dist(p,e)<w.range)damage(e,n);return}if(w.id==='meteor'){for(let i=0;i<w.shots;i++){const e=nearest(p.x+rand(-150,150),p.y+rand(-150,150),w.range);if(e){damage(e,n);burst(e.x,e.y,w.color,10)}}return}const base=Math.atan2(target.y-p.y,target.x-p.x);for(let i=0;i<w.shots;i++){const a=base+(i-(w.shots-1)/2)*(w.spread||0);game.shots.push({x:p.x,y:p.y,vx:Math.cos(a)*(w.speed||600),vy:Math.sin(a)*(w.speed||600),life:(w.range||700)/(w.speed||600),r:6,color:w.color,damage:n,pierce:w.pierce||0})}}
function weaponsUpdate(dt){const p=game.player;p.orbit+=dt*2;for(const w of p.weapons){if(w.id==='orbit')continue;w.cd-=dt;if(w.cd<=0){w.cd=Math.max(.1,w.rate*Math.pow(.9,w.level-1)*(1-game.cooldown));fire(w)}}}
function move(dt){const p=game.player;let x=(keys.a||keys.arrowleft?-1:0)+(keys.d||keys.arrowright?1:0),y=(keys.w||keys.arrowup?-1:0)+(keys.s||keys.arrowdown?1:0);if(touch.active){x=touch.x;y=touch.y}const m=Math.hypot(x,y);if(m){p.x+=x/m*p.speed*dt;p.y+=y/m*p.speed*dt}}
function shotsUpdate(dt){for(const b of game.shots){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;for(const e of game.enemies)if(e.hp>0&&b.life>0&&Math.hypot(b.x-e.x,b.y-e.y)<b.r+e.r){damage(e,b.damage);if(b.pierce)b.pierce--;else b.life=0}}game.shots=game.shots.filter(b=>b.life>0)}
function enemiesUpdate(dt){const p=game.player;for(const e of game.enemies){if(e.hp<=0)continue;const d=Math.max(.001,dist(e,p));if(e.kind==='ranged'&&d>280){e.shoot-=dt;if(e.shoot<=0){e.shoot=2;const a=Math.atan2(p.y-e.y,p.x-e.x);game.shots.push({x:e.x,y:e.y,vx:Math.cos(a)*260,vy:Math.sin(a)*260,life:3,r:5,color:'#60a5fa',enemy:true,damage:9})}}else if(d>e.r+p.r+4){e.x+=(p.x-e.x)/d*e.speed*dt;e.y+=(p.y-e.y)/d*e.speed*dt}else p.hp-= (e.boss?25:12)*(1-p.armor)*dt}for(const b of game.shots)if(b.enemy){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life>0&&Math.hypot(b.x-p.x,b.y-p.y)<p.r+b.r){p.hp-=b.damage;b.life=0}}game.shots=game.shots.filter(b=>b.life>0);game.enemies=game.enemies.filter(e=>e.hp>0)}
function collect(dt){const p=game.player;for(const g of game.gems){if(dist(g,p)<p.magnet+game.magnet){const d=Math.max(1,dist(g,p));g.x+=(p.x-g.x)/d*380*dt;g.y+=(p.y-g.y)/d*380*dt}if(dist(g,p)<p.r+10){game.xp+=g.v;g.dead=true}}game.gems=game.gems.filter(g=>!g.dead);if(game.xp>=game.nextXp){game.xp-=game.nextXp;game.level++;game.nextXp=Math.floor(game.nextXp*1.25+4);showUpgrade()}}
function particles(dt){game.parts.forEach(a=>{a.x+=a.vx*dt;a.y+=a.vy*dt;a.life-=dt});game.parts=game.parts.filter(a=>a.life>0);game.texts.forEach(a=>{a.y-=25*dt;a.life-=dt});game.texts=game.texts.filter(a=>a.life>0)}
function upgrade(id){const p=game.player;if(id==='damage')p.power*=1.2;if(id==='speed')p.speed*=1.15;if(id==='magnet')game.magnet+=35;if(id==='armor')p.armor=Math.min(.8,p.armor+.15);if(id==='maxhp'){p.maxHp+=20;p.hp=Math.min(p.maxHp,p.hp+20)}if(id==='cooldown')game.cooldown=Math.min(.7,game.cooldown+.1);if(Math.random()<.35&&p.weapons.length<4){const unused=weapons.filter(w=>!p.weapons.some(x=>x.id===w.id));if(unused.length){const w={...unused[Math.floor(Math.random()*unused.length)],level:1,cd:0};p.weapons.push(w);toast('NEW WEAPON: '+w.name)}}showOnly(ui.hud)}
function showUpgrade(){ui.grid.innerHTML='';const picks=[...upgrades].sort(()=>Math.random()-.5).slice(0,3);picks.forEach(u=>{const b=document.createElement('button');b.className='upgrade-card';b.innerHTML=`<span class="upgrade-icon">${u[2]}</span><strong>${u[1]}</strong><small>${u[3]}</small>`;b.onclick=()=>upgrade(u[0]);ui.grid.appendChild(b)});showOnly(ui.upgrade);ui.touch.classList.add('hidden')}
function updateHUD(){const p=game.player;if(!p)return;ui.level.textContent=game.level;ui.wave.textContent=game.wave;ui.time.textContent=fmt(game.t);ui.kills.textContent=game.kills;ui.hp.style.width=clamp(p.hp/p.maxHp,0,1)*100+'%';ui.xp.style.width=clamp(game.xp/game.nextXp,0,1)*100+'%';const boss=game.enemies.find(e=>e.boss);ui.boss.classList.toggle('hidden',!boss);if(boss)ui.bossHp.style.width=clamp(boss.hp/boss.maxHp,0,1)*100+'%'}
function endRun(){if(game.over)return;game.over=true;game.running=false;save.bestTime=Math.max(save.bestTime,game.t);save.bestLevel=Math.max(save.bestLevel,game.level);saveIt();$('finalTime').textContent=fmt(game.t);$('finalLevel').textContent=game.level;$('finalKills').textContent=game.kills;$('finalShards').textContent=game.xp;$('bestTime').textContent=fmt(save.bestTime);$('bestLevel').textContent=save.bestLevel;ui.touch.classList.add('hidden');showOnly(ui.gameover)}
function togglePause(){if(!game.running||game.over||game.upgradeOpen)return;game.paused=!game.paused;if(game.paused){showOnly(ui.pause);ui.touch.classList.add('hidden')}else{showOnly(ui.hud);ui.touch.classList.remove('hidden');game.last=performance.now()}}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#07101d';ctx.fillRect(0,0,W,H);if(!game.player)return;const p=game.player,sx=W/2-p.x+(Math.random()-.5)*game.shake,sy=H/2-p.y+(Math.random()-.5)*game.shake;ctx.save();ctx.translate(sx,sy);ctx.strokeStyle='rgba(120,170,220,.10)';ctx.lineWidth=1;const size=80,l= p.x-W/2-100,r=p.x+W/2+100,t=p.y-H/2-100,b=p.y+H/2+100;for(let x=Math.floor(l/size)*size;x<r;x+=size){ctx.beginPath();ctx.moveTo(x,t);ctx.lineTo(x,b);ctx.stroke()}for(let y=Math.floor(t/size)*size;y<b;y+=size){ctx.beginPath();ctx.moveTo(l,y);ctx.lineTo(r,y);ctx.stroke()}for(const g of game.gems){ctx.fillStyle='#67e8f9';ctx.beginPath();ctx.arc(g.x,g.y,5,0,7);ctx.fill()}for(const b of game.shots){ctx.fillStyle=b.color||'#fff';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.fill()}if(p.weapons.some(w=>w.id==='orbit'))for(let i=0;i<2;i++){const a=p.orbit+i*Math.PI,x=p.x+Math.cos(a)*105,y=p.y+Math.sin(a)*105;ctx.fillStyle='#f0abfc';ctx.beginPath();ctx.arc(x,y,9,0,7);ctx.fill()}for(const e of game.enemies){ctx.fillStyle=e.color;ctx.beginPath();ctx.arc(e.x,e.y,e.r,0,7);ctx.fill();if(e.hp<e.maxHp){ctx.fillStyle='#17202d';ctx.fillRect(e.x-e.r,e.y-e.r-9,e.r*2,4);ctx.fillStyle='#86efac';ctx.fillRect(e.x-e.r,e.y-e.r-9,e.r*2*clamp(e.hp/e.maxHp,0,1),4)}}ctx.fillStyle='#67e8f9';ctx.beginPath();ctx.moveTo(p.x+23,p.y);ctx.lineTo(p.x-13,p.y-14);ctx.lineTo(p.x-8,p.y);ctx.lineTo(p.x-13,p.y+14);ctx.closePath();ctx.fill();for(const a of game.parts){ctx.globalAlpha=clamp(a.life/.55,0,1);ctx.fillStyle=a.c;ctx.beginPath();ctx.arc(a.x,a.y,a.r,0,7);ctx.fill()}ctx.globalAlpha=1;for(const a of game.texts){ctx.globalAlpha=clamp(a.life/.6,0,1);ctx.fillStyle='#fff';ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.fillText(a.s,a.x,a.y)}ctx.restore();game.shake*=.88}
function loop(now){const dt=Math.min(.033,Math.max(0,(now-game.last)/1000));game.last=now;if(game.running&&!game.paused&&!game.over){game.t+=dt;game.wave=1+Math.floor(game.t/30);move(dt);spawn(dt);weaponsUpdate(dt);shotsUpdate(dt);enemiesUpdate(dt);collect(dt);particles(dt);if(game.player.hp<=0)endRun();updateHUD()}draw();requestAnimationFrame(loop)}
$('startBtn').addEventListener('click',reset);$('restartBtn').addEventListener('click',reset);$('pauseBtn').addEventListener('click',togglePause);$('resumeBtn').addEventListener('click',togglePause);$('quitBtn').addEventListener('click',()=>{game.running=false;showOnly(ui.menu);ui.touch.classList.add('hidden')});$('menuBtn').addEventListener('click',()=>{game.running=false;showOnly(ui.menu);ui.touch.classList.add('hidden')});
addEventListener('visibilitychange',()=>{if(document.hidden&&game.running&&!game.paused)togglePause()});
showOnly(ui.menu);ui.touch.classList.add('hidden');requestAnimationFrame(loop);
})();

addEventListener('error',e=>{const box=document.getElementById('runtimeError'),txt=document.getElementById('runtimeErrorText');if(box&&txt){txt.textContent=(e.error&&e.error.message)||e.message||'Unknown JavaScript error';box.classList.remove('hidden')}});
addEventListener('unhandledrejection',e=>{const box=document.getElementById('runtimeError'),txt=document.getElementById('runtimeErrorText');if(box&&txt){txt.textContent=(e.reason&&e.reason.message)||String(e.reason);box.classList.remove('hidden')}});
