const canvas=document.getElementById('game');const ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id);
const ui={menu:$('menu'),hud:$('hud'),upgrade:$('upgrade'),pause:$('pause'),gameover:$('gameover'),upgradeGrid:$('upgradeGrid'),level:$('level'),wave:$('wave'),time:$('time'),kills:$('kills'),hpBar:$('hpBar'),xpBar:$('xpBar'),bossBar:$('bossBar'),bossName:$('bossName'),bossHpBar:$('bossHpBar'),touch:$('touchControls'),joystick:$('joystick'),stick:$('stick'),toast:$('toast')};
let W=innerWidth,H=innerHeight,dpr=Math.min(devicePixelRatio||1,2);function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.floor(W*dpr);canvas.height=Math.floor(H*dpr);canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const rand=(a,b)=>a+Math.random()*(b-a);const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const saveKey='nebula-survivors-v2';let save;try{save=JSON.parse(localStorage.getItem(saveKey)||'null')}catch{save=null}save=save||{coins:0,bestTime:0,bestLevel:1,highestWave:1,damageBonus:0,speedBonus:0,maxHpBonus:0};function persist(){localStorage.setItem(saveKey,JSON.stringify(save))}
const WEAPONS=[
{id:'pulse',name:'Pulse Blaster',icon:'✦',color:'#67e8f9',rate:.48,damage:18,speed:620,spread:0,shots:1,range:900,kind:'bullet',desc:'A rapid crystal shot.'},{id:'shards',name:'Void Shards',icon:'◆',color:'#c4b5fd',rate:1.2,damage:34,speed:0,spread:Math.PI*.7,shots:3,range:260,kind:'fan',desc:'A three-way burst.'},{id:'orbit',name:'Orbit Blades',icon:'◈',color:'#f0abfc',rate:0,damage:24,speed:0,range:100,shots:2,kind:'orbit',desc:'Blades circle your ship.'},{id:'nova',name:'Solar Nova',icon:'✹',color:'#fb923c',rate:3.4,damage:70,speed:0,range:180,shots:1,kind:'nova',desc:'Explodes around the closest threat.'},{id:'frost',name:'Frost Field',icon:'❄',color:'#93c5fd',rate:2.4,damage:42,speed:0,range:145,shots:1,kind:'field',desc:'Freezes and damages nearby foes.'},{id:'arc',name:'Arc Lance',icon:'⚡',color:'#fde047',rate:1.65,damage:52,speed:820,range:780,shots:1,kind:'pierce',desc:'A beam-like bolt that can pierce.'},{id:'meteor',name:'Meteor Rain',icon:'☄',color:'#f97316',rate:4.7,damage:120,speed:0,range:230,shots:2,kind:'meteor',desc:'Calls meteors onto the swarm.'},{id:'drone',name:'Star Drones',icon:'✺',color:'#86efac',rate:1.7,damage:38,speed:520,range:700,shots:2,kind:'drone',desc:'Tiny seekers hunt targets.'}];
const UPGRADE_POOL=[{id:'damage',name:'Overcharge',icon:'⚔',desc:'+18% all weapon damage.',tag:'POWER'},{id:'speed',name:'Thrusters',icon:'➤',desc:'+14% movement speed.',tag:'MOBILITY'},{id:'magnet',name:'Singularity',icon:'◎',desc:'+28% shard pickup range.',tag:'UTILITY'},{id:'armor',name:'Phase Armor',icon:'◉',desc:'Reduce contact damage by 15%.',tag:'DEFENSE'},{id:'maxhp',name:'Reactor Core',icon:'♥',desc:'+18 maximum HP and heal 18.',tag:'SURVIVAL'},{id:'cooldown',name:'Rapid Circuit',icon:'⏱',desc:'Weapons fire 10% faster.',tag:'TEMPO'}];
let keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(e.key.toLowerCase()))e.preventDefault();if(e.key.toLowerCase()==='p')togglePause()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
let touch={active:false,cx:0,cy:0,x:0,y:0};function setStick(px,py){const r=52,dx=px-touch.cx,dy=py-touch.cy,m=Math.hypot(dx,dy)||1,s=Math.min(r,m);touch.x=dx/m*s/r;touch.y=dy/m*s/r;ui.stick.style.transform=`translate(${dx/m*s}px,${dy/m*s}px)`}ui.joystick.addEventListener('pointerdown',e=>{touch.active=true;ui.joystick.setPointerCapture(e.pointerId);const r=ui.joystick.getBoundingClientRect();touch.cx=r.left+r.width/2;touch.cy=r.top+r.height/2;setStick(e.clientX,e.clientY)});ui.joystick.addEventListener('pointermove',e=>touch.active&&setStick(e.clientX,e.clientY));const touchEnd=()=>{touch.active=false;touch.x=0;touch.y=0;ui.stick.style.transform='translate(0,0)'};ui.joystick.addEventListener('pointerup',touchEnd);ui.joystick.addEventListener('pointercancel',touchEnd);
const game={running:false,paused:false,over:false,time:0,kills:0,wave:1,level:1,xp:0,nextXp:12,shards:0,spawn:0,nextBoss:90,enemyId:0,projectileId:0,shake:0,cameraX:0,cameraY:0,last:performance.now(),enemies:[],projectiles:[],gems:[],particles:[],texts:[],player:null,cooldownBoost:0,magnetBoost:0};
function makePlayer(){return{x:0,y:0,r:18,hp:100+save.maxHpBonus,maxHp:100+save.maxHpBonus,speed:230*(1+save.speedBonus),magnet:100,pickup:100,armor:0,power:1+save.damageBonus,weapons:[{...structuredClone(WEAPONS[0]),level:1,cd:0}],orbitAngle:0}}
function reset(){game.running=true;game.paused=false;game.over=false;game.time=0;game.kills=0;game.wave=1;game.level=1;game.xp=0;game.nextXp=12;game.shards=0;game.spawn=0;game.nextBoss=90;game.enemyId=0;game.projectileId=0;game.shake=0;game.cameraX=0;game.cameraY=0;game.enemies=[];game.projectiles=[];game.gems=[];game.particles=[];game.texts=[];game.cooldownBoost=0;game.magnetBoost=0;game.player=makePlayer();showOnly(ui.hud);ui.touch.classList.remove('hidden');updateHUD();beep(440,.07,'triangle',.018)}
function showOnly(target){[ui.menu,ui.hud,ui.upgrade,ui.pause,ui.gameover].forEach(x=>x.classList.add('hidden'));target.classList.remove('hidden')}
function fmt(t){const s=Math.max(0,Math.floor(t));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function toast(text){ui.toast.textContent=text;ui.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.toast.classList.add('hidden'),1700)}
function spawnEnemy(kind){const ang=rand(0,Math.PI*2),radius=Math.max(W,H)*.72+rand(100,380),x=game.player.x+Math.cos(ang)*radius,y=game.player.y+Math.sin(ang)*radius;const scale=1+game.time/150;const data={grunt:[34,52,14,'#45e0a8',1],runner:[23,112,11,'#fb7185',1.5],brute:[120,38,24,'#94a3b8',3],ranged:[70,42,16,'#60a5fa',2],elite:[420,58,30,'#a78bfa',10],boss:[2200+game.time*18,34,52,'#ef4444',40]};const d=data[kind]||data.grunt;game.enemies.push({id:++game.enemyId,x,y,hp:d[0]*scale,maxHp:d[0]*scale,speed:d[1]*(1+game.time*.0015),r:d[2],color:d[3],kind,value:d[4],hit:0,shoot:rand(1,3),boss:kind==='boss'})}
function maybeSpawn(dt){game.spawn-=dt;if(game.spawn<=0){game.spawn=Math.max(.14,.72-game.time*.0025);const count=game.time>120?3:game.time>60?2:1;for(let i=0;i<count;i++){const r=Math.random();const kind=game.time>75&&r<.025?'elite':game.time>45&&r<.12?'brute':game.time>25&&r<.24?'runner':game.time>35&&r<.34?'ranged':'grunt';spawnEnemy(kind)}}if(game.time>=game.nextBoss){spawnEnemy('boss');game.nextBoss+=90;toast('BOSS INBOUND — WARDEN PRIME')}}
function nearest(x,y,max=Infinity){let best=null,bd=max;for(const e of game.enemies){if(e.hp<=0)continue;const d=Math.hypot(e.x-x,e.y-y);if(d<bd){best=e;bd=d}}return best}
function addText(x,y,text,color='#fff',life=.7){game.texts.push({x,y,text,color,life,max:life})}function burst(x,y,color,count=8,power=100){for(let i=0;i<count;i++){const a=rand(0,Math.PI*2),s=rand(power*.35,power);game.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rand(.3,.65),max:.65,color,r:rand(1.5,4.5)})}}
function hitEnemy(e,dmg){if(!e||e.hp<=0)return;e.hp-=dmg;e.hit=.08;addText(e.x+rand(-8,8),e.y-e.r-5,Math.round(dmg),e.boss?'#fecaca':'#fef3c7',.55);burst(e.x,e.y,e.color,e.boss?7:3,60);game.shake=Math.max(game.shake,e.boss?5:1.5);if(e.hp<=0){game.kills++;game.shards+=e.value;const count=e.boss?15:e.kind==='elite'?4:1;for(let i=0;i<count;i++)game.gems.push({x:e.x+rand(-10,10),y:e.y+rand(-10,10),value:e.boss?4:e.value,phase:rand(0,6)});save.coins+=e.boss?25:e.value;burst(e.x,e.y,e.color,e.boss?25:10,e.boss?180:100);if(e.boss)beep(90,.2,'sawtooth',.03);else beep(220,.025,'square',.008)}}
function fireWeapon(w){const p=game.player,target=nearest(p.x,p.y,w.range||Infinity);if(w.kind==='orbit')return;if(w.kind==='nova'){if(target){for(const e of game.enemies)if(dist(target,e)<w.range)hitEnemy(e,w.damage*p.power*(1+.18*(w.level-1)));burst(target.x,target.y,w.color,20,150)}return}if(w.kind==='field'){for(const e of game.enemies)if(dist(p,e)<w.range)hitEnemy(e,w.damage*p.power*(1+.1*(w.level-1)));return}if(w.kind==='meteor'){for(let i=0;i<w.shots;i++){const e=nearest(p.x+rand(-130,130),p.y+rand(-130,130),w.range);if(e){setTimeout(()=>{if(game.running&&e.hp>0)hitEnemy(e,w.damage*p.power*(1+.15*(w.level-1)))},60+i*90);burst(e.x,e.y,w.color,10,90)}}return}if(!target)return;const baseAngle=Math.atan2(target.y-p.y,target.x-p.x);for(let i=0;i<w.shots;i++){const spread=w.spread||0;const a=baseAngle+(i-(w.shots-1)/2)*(spread/Math.max(1,w.shots-1));game.projectiles.push({id:++game.projectileId,x:p.x,y:p.y,vx:Math.cos(a)*w.speed,vy:Math.sin(a)*w.speed,damage:w.damage*p.power*(1+.12*(w.level-1)),life:(w.range||700)/(w.speed||1),r:6,color:w.color,pierce:w.kind==='pierce'?2:0})}}
function updateWeapons(dt){const p=game.player;p.orbitAngle+=dt*1.4;for(const w of p.weapons){if(w.kind==='orbit')continue;w.cd-=dt;if(w.cd<=0){w.cd=Math.max(.18,w.rate*Math.pow(.91,w.level-1)*(1-game.cooldownBoost));fireWeapon(w)}}}
function movement(dt){const p=game.player;let dx=(keys.a||keys.arrowleft?-1:0)+(keys.d||keys.arrowright?1:0),dy=(keys.w||keys.arrowup?-1:0)+(keys.s||keys.arrowdown?1:0);if(touch.active){dx=touch.x;dy=touch.y}const m=Math.hypot(dx,dy)||1;p.x+=dx/m*p.speed*dt;p.y+=dy/m*p.speed*dt;game.cameraX+=(p.x-game.cameraX)*Math.min(1,dt*6);game.cameraY+=(p.y-game.cameraY)*Math.min(1,dt*6)}
function updateProjectiles(dt){for(const b of game.projectiles){if(b.enemy)continue;b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0)continue;for(const e of game.enemies){if(e.hp<=0||b.life<=0)continue;if(Math.hypot(b.x-e.x,b.y-e.y)<e.r+b.r){hitEnemy(e,b.damage);if(b.pierce>0)b.pierce--;else b.life=0}}}game.projectiles=game.projectiles.filter(b=>b.life>0)}
function updateEnemyProjectiles(dt){const p=game.player;for(const b of game.projectiles){if(!b.enemy)continue;b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0)continue;if(Math.hypot(b.x-p.x,b.y-p.y)<p.r+b.r){p.hp-=b.damage;b.life=0;game.shake=4}}game.projectiles=game.projectiles.filter(b=>b.life>0)}
function updateEnemies(dt){const p=game.player;for(const e of game.enemies){if(e.hp<=0)continue;e.hit=Math.max(0,e.hit-dt);const d=Math.max(.001,dist(e,p));if(e.kind==='ranged'&&d>260){e.shoot-=dt;if(e.shoot<=0){e.shoot=2.5;const a=Math.atan2(p.y-e.y,p.x-e.x);game.projectiles.push({x:e.x,y:e.y,vx:Math.cos(a)*250,vy:Math.sin(a)*250,damage:8+game.time*.06,life:3,r:5,color:'#60a5fa',pierce:0,enemy:true})}}else if(d>e.r+p.r+5){e.x+=(p.x-e.x)/d*e.speed*dt;e.y+=(p.y-e.y)/d*e.speed*dt}else if(d<e.r+p.r+7){p.hp-=Math.max(.1,(e.kind==='boss'?28:12)*(1-p.armor)*dt);if(Math.random()<.08)game.shake=3}}}
function collect(dt){const p=game.player;for(const g of game.gems){g.phase+=dt*4;const d=dist(g,p);if(d<p.magnet){const n=Math.max(1,d);g.x+=(p.x-g.x)/n*(320+game.magnetBoost)*dt;g.y+=(p.y-g.y)/n*(320+game.magnetBoost)*dt}if(dist(g,p)<p.r+10){game.xp+=g.value;g.dead=true}}game.gems=game.gems.filter(g=>!g.dead);while(game.xp>=game.nextXp){game.xp-=game.nextXp;game.level++;game.nextXp=Math.floor(game.nextXp*1.23+5);showUpgrade();if(game.paused)break}}
function updateParticles(dt){for(const a of game.particles){a.x+=a.vx*dt;a.y+=a.vy*dt;a.vx*=Math.pow(.04,dt);a.vy*=Math.pow(.04,dt);a.life-=dt}game.particles=game.particles.filter(a=>a.life>0);for(const t of game.texts){t.y-=24*dt;t.life-=dt}game.texts=game.texts.filter(t=>t.life>0)}
function drawGrid(){const left=game.cameraX-W*.7,right=game.cameraX+W*.7,top=game.cameraY-H*.7,bottom=game.cameraY+H*.7;ctx.fillStyle='#050b15';ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(W/2-game.cameraX,H/2-game.cameraY);ctx.strokeStyle='rgba(66,101,139,.13)';ctx.lineWidth=1;const s=80;for(let x=Math.floor(left/s)*s;x<right;x+=s){ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,bottom);ctx.stroke()}for(let y=Math.floor(top/s)*s;y<bottom;y+=s){ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke()}for(let i=-5;i<=5;i++){ctx.beginPath();ctx.arc(game.player.x,game.player.y,140+i*50,0,Math.PI*2);ctx.strokeStyle=`rgba(96,165,250,${i===0?.06:.018})`;ctx.stroke()}ctx.restore()}
function drawWorld(){ctx.save();ctx.translate(W/2-game.cameraX,H/2-game.cameraY);const p=game.player;for(const g of game.gems){ctx.save();ctx.translate(g.x,g.y);ctx.rotate(g.phase);ctx.fillStyle='#7dd3fc';ctx.shadowBlur=14;ctx.shadowColor='#67e8f9';ctx.beginPath();ctx.moveTo(0,-6);ctx.lineTo(5,0);ctx.lineTo(0,6);ctx.lineTo(-5,0);ctx.closePath();ctx.fill();ctx.restore()}for(const e of game.enemies){if(e.hp<=0)continue;ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle=e.hit>0?'#fff':e.color;ctx.shadowBlur=e.boss?28:10;ctx.shadowColor=e.color;ctx.beginPath();const sides=e.boss?10:e.kind==='elite'?7:6;for(let i=0;i<sides;i++){const a=i/sides*Math.PI*2-Math.PI/2,r=e.r*(1+(i%2)*.08);i?ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r):ctx.moveTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();ctx.fill();if(e.boss||e.kind==='elite'){ctx.shadowBlur=0;ctx.fillStyle='#1e293b';ctx.fillRect(-e.r,-e.r-10,e.r*2,5);ctx.fillStyle=e.boss?'#f87171':'#c4b5fd';ctx.fillRect(-e.r,-e.r-10,e.r*2*clamp(e.hp/e.maxHp,0,1),5)}ctx.restore()}for(const b of game.projectiles){if(b.enemy)continue;ctx.save();ctx.translate(b.x,b.y);ctx.fillStyle=b.color;ctx.shadowBlur=16;ctx.shadowColor=b.color;ctx.beginPath();ctx.arc(0,0,b.r,0,Math.PI*2);ctx.fill();ctx.restore()}for(const b of game.projectiles){if(!b.enemy)continue;ctx.save();ctx.translate(b.x,b.y);ctx.fillStyle='#60a5fa';ctx.shadowBlur=12;ctx.shadowColor='#60a5fa';ctx.beginPath();ctx.arc(0,0,b.r,0,Math.PI*2);ctx.fill();ctx.restore()}for(const w of p.weapons)if(w.kind==='orbit'){for(let i=0;i<w.shots;i++){const a=p.orbitAngle+i*Math.PI*2/w.shots;const x=p.x+Math.cos(a)*w.range,y=p.y+Math.sin(a)*w.range;ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.fillStyle=w.color;ctx.shadowBlur=18;ctx.shadowColor=w.color;ctx.beginPath();ctx.moveTo(0,-13);ctx.lineTo(7,9);ctx.lineTo(0,6);ctx.lineTo(-7,9);ctx.closePath();ctx.fill();ctx.restore();for(const e of game.enemies)if(e.hp>0&&Math.hypot(e.x-x,e.y-y)<e.r+12)hitEnemy(e,w.damage*p.power*dt*4)}}for(const a of game.particles){ctx.globalAlpha=a.life/a.max;ctx.fillStyle=a.color;ctx.beginPath();ctx.arc(a.x,a.y,a.r,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.save();ctx.translate(p.x,p.y);ctx.shadowBlur=28;ctx.shadowColor='#38bdf8';const grd=ctx.createRadialGradient(0,0,3,0,0,26);grd.addColorStop(0,'#fff');grd.addColorStop(.25,'#67e8f9');grd.addColorStop(1,'#2563eb');ctx.fillStyle=grd;ctx.beginPath();ctx.arc(0,0,p.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#dbeafe';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-22);ctx.lineTo(6,4);ctx.lineTo(0,11);ctx.lineTo(-6,4);ctx.closePath();ctx.stroke();ctx.restore();for(const t of game.texts){ctx.globalAlpha=t.life/t.max;ctx.fillStyle=t.color;ctx.font='800 13px system-ui';ctx.textAlign='center';ctx.fillText(t.text,t.x,t.y)}ctx.globalAlpha=1;ctx.restore()}
function drawBoss(){const boss=game.enemies.find(e=>e.boss&&e.hp>0);ui.bossBar.classList.toggle('hidden',!boss);if(boss){ui.bossName.textContent='WARDEN PRIME';ui.bossHpBar.style.width=`${clamp(boss.hp/boss.maxHp*100,0,100)}%`}}
function render(){ctx.save();if(game.shake>0)ctx.translate(rand(-game.shake,game.shake),rand(-game.shake,game.shake));drawGrid();drawWorld();ctx.restore();drawBoss()}
function updateHUD(){const p=game.player;if(!p)return;ui.level.textContent=game.level;ui.wave.textContent=game.wave;ui.time.textContent=fmt(game.time);ui.kills.textContent=game.kills;ui.hpBar.style.width=`${clamp(p.hp/p.maxHp*100,0,100)}%`;ui.xpBar.style.width=`${clamp(game.xp/game.nextXp*100,0,100)}%`}
function chooseUpgrades(){const p=game.player;const choices=[];for(const w of p.weapons)choices.push({type:'weapon',item:w,id:w.id,name:w.name,icon:w.icon,desc:`Level ${w.level} → ${w.level+1}. More damage and better effects.`,tag:'WEAPON'});for(const w of WEAPONS.filter(x=>!p.weapons.some(y=>y.id===x.id)))choices.push({type:'weapon',item:w,id:w.id,name:w.name,icon:w.icon,desc:w.desc,tag:'NEW WEAPON'});for(const u of UPGRADE_POOL)choices.push({type:'stat',...u});for(let i=choices.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[choices[i],choices[j]]=[choices[j],choices[i]]}return choices.slice(0,3)}
function showUpgrade(){game.paused=true;const choices=chooseUpgrades();ui.upgradeGrid.innerHTML='';for(const c of choices){const b=document.createElement('button');b.className='upgrade-choice';b.innerHTML=`<div class="icon">${c.icon}</div><h3>${c.name}</h3><p>${c.desc}</p><span class="tag">${c.tag}</span>`;b.onclick=()=>applyChoice(c);ui.upgradeGrid.appendChild(b)}showOnly(ui.upgrade);ui.touch.classList.add('hidden')}
function applyChoice(c){const p=game.player;if(c.type==='weapon'){let w=p.weapons.find(x=>x.id===c.id);if(!w){w={...structuredClone(c.item),level:1,cd:0};p.weapons.push(w);toast(`${w.name} acquired`)}else{w.level++;w.damage*=1.18;w.shots+=w.level%3===0?1:0;w.range+=w.kind==='orbit'?8:20;if(w.level===5)toast(`${w.name} evolved!`);else toast(`${w.name} upgraded`)}}else{switch(c.id){case'damage':p.power*=1.18;break;case'speed':p.speed*=1.14;break;case'magnet':p.magnet*=1.28;game.magnetBoost+=45;break;case'armor':p.armor=Math.min(.7,p.armor+.15);break;case'maxhp':p.maxHp+=18;p.hp=Math.min(p.maxHp,p.hp+18);break;case'cooldown':game.cooldownBoost=Math.min(.45,game.cooldownBoost+.1);break}}game.paused=false;showOnly(ui.hud);ui.touch.classList.remove('hidden');updateHUD();beep(620,.08,'triangle',.02)}
function togglePause(){if(!game.running||game.over)return;if(!ui.upgrade.classList.contains('hidden'))return;game.paused=!game.paused;if(game.paused){showOnly(ui.pause);ui.touch.classList.add('hidden')}else{showOnly(ui.hud);ui.touch.classList.remove('hidden')}}
function endRun(){game.over=true;game.running=false;ui.touch.classList.add('hidden');save.bestTime=Math.max(save.bestTime,game.time);save.bestLevel=Math.max(save.bestLevel,game.level);save.highestWave=Math.max(save.highestWave,game.wave);persist();$('finalTime').textContent=fmt(game.time);$('finalLevel').textContent=game.level;$('finalKills').textContent=game.kills;$('finalShards').textContent=game.shards;$('bestTime').textContent=fmt(save.bestTime);$('bestLevel').textContent=save.bestLevel;$('gameoverTitle').textContent=game.time>300?'Legendary run.':'The swarm wins.';showOnly(ui.gameover);beep(70,.35,'sawtooth',.03)}
$('startBtn').onclick=()=>{audioUnlock();reset()};$('pauseBtn').onclick=togglePause;$('resumeBtn').onclick=()=>{game.paused=false;showOnly(ui.hud);ui.touch.classList.remove('hidden')};$('quitBtn').onclick=()=>{game.running=false;showOnly(ui.menu);ui.touch.classList.add('hidden')};$('restartBtn').onclick=()=>{audioUnlock();reset()};$('menuBtn').onclick=()=>{game.running=false;showOnly(ui.menu);ui.touch.classList.add('hidden')};
let audioCtx=null;function audioUnlock(){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume()}catch{}}function beep(freq,dur=.05,type='sine',gain=.015){if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=gain;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.stop(audioCtx.currentTime+dur)}
function tick(dt){if(!game.running||game.paused||game.over)return;game.time+=dt;game.wave=1+Math.floor(game.time/30);movement(dt);maybeSpawn(dt);updateWeapons(dt);updateProjectiles(dt);updateEnemyProjectiles(dt);updateEnemies(dt);collect(dt);updateParticles(dt);game.shake=Math.max(0,game.shake-dt*12);if(game.player.hp<=0){endRun();return}updateHUD()}
function loop(now){const dt=Math.min(.033,(now-game.last)/1000);game.last=now;tick(dt);render();requestAnimationFrame(loop)}requestAnimationFrame(loop);showOnly(ui.menu);