(() => {
  'use strict';
  function boot() {
    const $ = id => document.getElementById(id);
    const canvas = $('game');
    const ctx = canvas && canvas.getContext('2d');
    if (!canvas || !ctx) return;
    const hud=$('hud'), menu=$('menu'), upgrade=$('upgrade'), pause=$('pause'), gameover=$('gameover'), error=$('runtimeError');
    const level=$('level'), wave=$('wave'), timeEl=$('time'), killsEl=$('kills'), hp=$('hpBar'), xp=$('xpBar');
    let w=innerWidth,h=innerHeight,dpr=1,last=performance.now(),running=false,paused=false,t=0,kills=0,levelN=1,xpN=0,nextXp=8,spawnTimer=0;
    const p={x:0,y:0,r:22,hp:100,maxHp:100,speed:260,damage:25};
    const enemies=[], bullets=[], gems=[], keys={};
    function resize(){w=Math.max(320,innerWidth);h=Math.max(240,innerHeight);dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
    function panels(show){[menu,hud,upgrade,pause,gameover,error].forEach(x=>x&&x.classList.add('hidden'));if(show)show.classList.remove('hidden')}
    function spawn(){const a=Math.random()*Math.PI*2,r=280+Math.random()*170;enemies.push({x:p.x+Math.cos(a)*r,y:p.y+Math.sin(a)*r,r:15,hp:3,maxHp:3,s:55+Math.random()*35})}
    function start(){p.x=0;p.y=0;p.hp=100;t=0;kills=0;levelN=1;xpN=0;nextXp=8;spawnTimer=.05;enemies.length=0;bullets.length=0;gems.length=0;for(let i=0;i<5;i++)spawn();running=true;paused=false;panels(hud);$('touchControls')?.classList.remove('hidden');last=performance.now()}
    function shoot(){if(!enemies.length)return;let target=enemies[0],bd=Infinity;for(const e of enemies){const d=Math.hypot(e.x-p.x,e.y-p.y);if(d<bd){bd=d;target=e}}const a=Math.atan2(target.y-p.y,target.x-p.x);bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*650,vy:Math.sin(a)*650,r:6,life:1.5})}
    function gainXP(v){xpN+=v;if(xpN>=nextXp){xpN-=nextXp;levelN++;nextXp=Math.floor(nextXp*1.3+3);showUpgrade()}}
    function showUpgrade(){if(!upgrade)return;const grid=$('upgradeGrid');if(!grid)return;grid.innerHTML='';[['OVERCHARGE','Damage +30%',()=>p.damage*=1.3],['THRUSTERS','Speed +20%',()=>p.speed*=1.2],['REACTOR','Max HP +30',()=>{p.maxHp+=30;p.hp=p.maxHp}],['TWIN SHOT','Fire two shots',()=>p.damage*=1.15]].sort(()=>Math.random()-.5).slice(0,3).forEach(([a,b,fn])=>{const x=document.createElement('button');x.className='upgrade-choice';x.type='button';x.innerHTML='<span class="icon">✦</span><h3>'+a+'</h3><p>'+b+'</p>';x.onclick=()=>{fn();paused=false;panels(hud);last=performance.now()};grid.appendChild(x)});paused=true;panels(upgrade);$('touchControls')?.classList.add('hidden')}
    function update(dt){if(!running||paused)return;t+=dt;let dx=(keys.a||keys.arrowleft?-1:0)+(keys.d||keys.arrowright?1:0),dy=(keys.w||keys.arrowup?-1:0)+(keys.s||keys.arrowdown?1:0),n=Math.hypot(dx,dy)||1;p.x+=dx/n*p.speed*dt;p.y+=dy/n*p.speed*dt;
      spawnTimer-=dt;if(spawnTimer<=0){spawnTimer=.7;spawn()};if(t>0.15) { if(!update.lastShot||t-update.lastShot>.42){update.lastShot=t;shoot()} }
      for(const b of bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;for(const e of enemies)if(e.hp>0&&Math.hypot(b.x-e.x,b.y-e.y)<b.r+e.r){e.hp=0;b.life=0;kills++;gainXP(1);gems.push({x:e.x,y:e.y})}}
      for(const e of enemies){if(e.hp<=0)continue;const ex=p.x-e.x,ey=p.y-e.y,d=Math.hypot(ex,ey)||1;if(d>e.r+p.r){e.x+=ex/d*e.s*dt;e.y+=ey/d*e.s*dt}else p.hp-=8*dt}
      for(const g of gems){const d=Math.hypot(g.x-p.x,g.y-p.y);if(d<130){g.x+=(p.x-g.x)/Math.max(d,1)*300*dt;g.y+=(p.y-g.y)/Math.max(d,1)*300*dt}if(d<30)g.dead=true}enemies.splice(0,enemies.length,...enemies.filter(e=>e.hp>0));bullets.splice(0,bullets.length,...bullets.filter(b=>b.life>0));gems.splice(0,gems.length,...gems.filter(g=>!g.dead));if(p.hp<=0){running=false;panels(gameover)}
      level.textContent=levelN;wave.textContent=1+Math.floor(t/30);timeEl.textContent=String(Math.floor(t/60)).padStart(2,'0')+':'+String(Math.floor(t%60)).padStart(2,'0');killsEl.textContent=kills;hp.style.width=(p.hp/p.maxHp*100)+'%';xp.style.width=(xpN/nextXp*100)+'%'}
    function draw(){ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#030711';ctx.fillRect(0,0,w,h);const g=ctx.createRadialGradient(w/2,h/2,0,w/2,h/2,Math.max(w,h)*.75);g.addColorStop(0,'#15385a');g.addColorStop(.55,'#081527');g.addColorStop(1,'#030711');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);const cx=w/2,cy=h/2;ctx.save();ctx.translate(cx-p.x,cy-p.y);ctx.strokeStyle='rgba(120,200,255,.13)';for(let x=-2000;x<2000;x+=90){ctx.beginPath();ctx.moveTo(x,-2000);ctx.lineTo(x,2000);ctx.stroke()}for(let y=-2000;y<2000;y+=90){ctx.beginPath();ctx.moveTo(-2000,y);ctx.lineTo(2000,y);ctx.stroke()};for(const g of gems){ctx.fillStyle='#67e8f9';ctx.shadowBlur=18;ctx.shadowColor='#67e8f9';ctx.beginPath();ctx.arc(g.x,g.y,6,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}for(const b of bullets){ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill()}for(const e of enemies){ctx.fillStyle='#45e0a8';ctx.shadowBlur=14;ctx.shadowColor='#45e0a8';ctx.beginPath();ctx.arc(e.x,e.y,e.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}ctx.restore();ctx.save();ctx.translate(cx,cy);ctx.fillStyle='#67e8f9';ctx.shadowBlur=30;ctx.shadowColor='#67e8f9';ctx.beginPath();ctx.moveTo(29,0);ctx.lineTo(-17,-16);ctx.lineTo(-8,0);ctx.lineTo(-17,16);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(2,0,6,0,Math.PI*2);ctx.fill();ctx.restore()}
    $('startBtn')?.addEventListener('click',start);$('restartBtn')?.addEventListener('click',start);$('pauseBtn')?.addEventListener('click',()=>{if(running){paused=true;panels(pause)}});$('resumeBtn')?.addEventListener('click',()=>{paused=false;panels(hud);last=performance.now()});$('quitBtn')?.addEventListener('click',()=>{running=false;panels(menu)});$('menuBtn')?.addEventListener('click',()=>{running=false;panels(menu)});
    addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='p'&&running){paused=!paused;panels(paused?pause:hud);last=performance.now()}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);addEventListener('resize',resize);
    resize();panels(menu);draw();requestAnimationFrame(function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;try{update(dt);draw()}catch(e){running=false;if(error){error.classList.remove('hidden');const m=$('runtimeErrorText');if(m)m.textContent=e.message||String(e)}}requestAnimationFrame(loop)});
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
